services:
  svelte-app:
    container_name: creepy0964-card
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site.rule=Host(`creepy0964.xyz`)"
      - "traefik.http.routers.site.entrypoints=websecure"
      - "traefik.http.services.site.loadbalancer.server.port=3838"
      - "traefik.http.routers.site.tls=true"

  traefik:
    image: traefik:v3.6
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"
      - "--providers.docker.network=homelab"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/server/ksmp-certs/global:/certs:ro
      - ./dynamic:/etc/traefik/dynamic:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.creepy0964.xyz`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"